apiVersion: v1
kind: Service
metadata:
  name: emissary-ingress
  namespace: emissary-system
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/name: emissary-ingress
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8080
    - name: https
      protocol: TCP
      port: 443
      targetPort: 8443
