apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: v3train-tls-cert
spec:
  secretName: v3train-tls
  issuerRef:
    name: letsencrypt-prod    
    kind: ClusterIssuer
  dnsNames:
    - "v3train.eastus.cloudapp.azure.com"