apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: v2train-tls-cert
spec:
  secretName: v2train-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - "v2train.eastus.cloudapp.azure.com"