name: Deploy AKS Cluster 

on: 
    push: 
        branches: 
          - main 
jobs:  
    
  deploy: 
    runs-on: ubuntu-latest 

    permissions: 
      id-token: write 
      contents: read
      
    steps: 
      - name: Checkout code 
        uses: actions/checkout@v2 
             
      - name: Set up Terraform 
        uses: hashicorp/setup-terraform@v2 
            
      - name: Azure Login
        uses: Azure/login@v1
        with:
            # ClientId of the Azure Service principal created.
            client-id: ${{secrets.SERVICE_PRINCIPAL_CLIENT_ID}}
            # TenantId of the Azure Service principal created.
            tenant-id: ${{secrets.TENANT_ID}}
            # Azure subscriptionId
            subscription-id: ${{secrets.SUBSCRIPTION_ID}}
    
      - name: Set TF_LOG environment variable
        run: echo "TF_LOG=DEBUG >> $GITHUB_ENV"

      - name: Terraform Init 
        run: |
            cd TF
            terraform init \
            -backend-config="storage_account_name=${{ secrets.STORAGE_ACCOUNT }}" \
            -backend-config="container_name=tfstate" \
            -backend-config="key=terraform.tfstate" \
            -backend-config="access_key=${{ secrets.REMOTE_STORAGE_KEY }}"
              
      - name: Terraform Plan 
        run: |
            cd TF
            terraform plan -out=plan.out 
              
      - name: Terraform Apply 
        run: |
            cd TF
            terraform apply -input=false plan.out 
        env: 
          TF_VAR_subscription_id: ${{ secrets.SUBSCRIPTION_ID }} 
          TF_VAR_resource_group_name: v2train
          TF_VAR_location: eastus 
          TF_VAR_cluster_name: v2train
          TF_VAR_service_principal_client_id: ${{ secrets.SERVICE_PRINCIPAL_CLIENT_ID }} 
          TF_VAR.service_principal_client_secret: ${{ secrets.SERVICE_PRINCIPAL_CLIENT_SECRET }} 
          TF_VAR_key_vault_name: v2train
          TF_VAR_servicebus_namespace_name: v2train
          TF_VAR_cosmosdb_account_name: v2train
          TF_VAR.admin_username: github         
