name: Deploy Emissary-ingress

on: [workflow_dispatch]

jobs:
  install-emissary-ingress:
    runs-on: ubuntu-latest
    
    permissions: 
      id-token: write 
      contents: read
      
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Kubernetes
        uses: azure/setup-kubectl@v1

      - name: Set up Helm
        uses: azure/setup-helm@v1

      - name: Azure Login
        uses: Azure/login@v1
        with:
            # ClientId of the Azure Service principal created.
            client-id: ${{secrets.SERVICE_PRINCIPAL_CLIENT_ID}}
            # TenantId of the Azure Service principal created.
            tenant-id: ${{secrets.TENANT_ID}}
            # Azure subscriptionId
            subscription-id: ${{secrets.SUBSCRIPTION_ID}}  

      - name: Set AKS context
        run: az aks get-credentials --name ${{ secrets.APP_NAME }} --resource-group ${{ secrets.APP_NAME }}

      - name: Ensure Helm config directory
        run: |
          mkdir -p ~/.helm/repository
          touch ~/.helm/repository/repositories.yaml
    
      - name: Add Helm repo
        run: |
          helm repo add datawire https://app.getambassador.io
          helm install datawire/ambassador
               
      - name: Refresh Helm Repositories 
        run: helm repo update

      - name: Apply Emissary CRDs
        run: |
          kubectl apply -f https://app.getambassador.io/yaml/emissary/3.3.0/emissary-crds.yaml
          kubectl wait --timeout=90s --for=condition=available deployment emissary-apiext -n emissary-system

      - name: Install Emissary-ingress
        run: |
          namespace="emissary"
          appname="${{ secrets.APP_NAME }}"
          helm install emissary-ingress datawire/emissary-ingress --set service.annotations."service\.beta\.kubernetes\.io/azure-dns-label-name"=$appname -n $namespace --create-namespace
          kubectl rollout status deployment/emissary-ingress -n $namespace -w

      - name: Configure Emissary-ingress routing
        run: |
          namespace="emissary"
          kubectl apply -f ./emissary-ingress/listener.yaml -n $namespace
          kubectl apply -f ./emissary-ingress/mappings.yaml -n $namespace
